services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spaget-app
    volumes:
      - ./app:/var/www/html:delegated
    depends_on:
      - db
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: "mysql://spaget:spaget@db:3306/spaget_db?serverVersion=8"

  web:
    image: nginx:latest
    container_name: spaget-web
    depends_on:
      - app
    ports:
      - "8082:80"
    volumes:
      - ./app:/var/www/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d

  db:
    image: mysql:8.0
    container_name: spaget-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: spaget_db
      MYSQL_USER: spaget
      MYSQL_PASSWORD: spaget
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: spaget-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpwd
    ports:
      - "8083:80"

volumes:
  db_data:
